package api

import (
	"fmt"
	"strings"

	"validator-backend/internal/models"
)

// BuildLLMPayload renders the "Copy to LLM" markdown for an idea using its
// latest scout cycle. The format mirrors the Validator UI's specification:
//
//	# IDEA: <title>
//
//	## DESCRIPTION
//	<description>
//
//	## SEARCH RADIUS METADATA
//	**Keywords:** ...
//	**Channels:** ...
//	**Scouting Frequency:** Every N days
//	**Custom Sources:** ...
//
//	## CYCLE: <label> (Day N)
//	### RAW PROS FOUND:
//	...
//	### RAW CONS FOUND:
//	...
//	---
//	*Generated by Validator - Agentic Market Research*
func BuildLLMPayload(idea *models.Idea, run *models.ScoutRun, signals []models.MarketSignal) string {
	var b strings.Builder

	pros, cons := splitSignals(signals)

	fmt.Fprintf(&b, "# IDEA: %s\n\n", idea.Title)
	fmt.Fprintf(&b, "## DESCRIPTION\n%s\n\n", idea.Description)

	b.WriteString("## SEARCH RADIUS METADATA\n")
	fmt.Fprintf(&b, "**Keywords:** %s\n", joinOrNone(idea.Keywords))
	fmt.Fprintf(&b, "**Channels:** %s\n", joinOrNone(idea.Channels))
	fmt.Fprintf(&b, "**Scouting Frequency:** Every %d %s\n",
		idea.FrequencyDays, pluralize("day", idea.FrequencyDays))

	if len(idea.CustomChannels) > 0 {
		b.WriteString("**Custom Sources:**\n")
		for _, c := range idea.CustomChannels {
			fmt.Fprintf(&b, "- %s: %s\n", c.Label, c.URL)
		}
	}
	b.WriteString("\n")

	cycleLabel := "Latest Scan"
	day := 0
	if run != nil {
		cycleLabel = run.Label
		day = run.DayNumber
	}
	fmt.Fprintf(&b, "## CYCLE: %s (Day %d)\n\n", cycleLabel, day)

	b.WriteString("### RAW PROS FOUND:\n")
	writeSignalSection(&b, pros, "Pro")
	b.WriteString("\n")

	b.WriteString("### RAW CONS FOUND:\n")
	writeSignalSection(&b, cons, "Con")
	b.WriteString("\n")

	b.WriteString("---\n")
	b.WriteString("*Generated by Validator - Agentic Market Research*\n")

	return b.String()
}

func writeSignalSection(b *strings.Builder, sigs []models.MarketSignal, polarity string) {
	if len(sigs) == 0 {
		b.WriteString("_No signals found this cycle._\n")
		return
	}
	for _, s := range sigs {
		fmt.Fprintf(b, "[%s] %s\n", strings.ToUpper(string(s.Platform)), s.SourceURL)
		fmt.Fprintf(b, "> \"%s\"\n", s.Quote)
		fmt.Fprintf(b, "**Why it's a %s:** %s\n\n", polarity, s.Reason)
	}
}

func splitSignals(in []models.MarketSignal) (pros, cons []models.MarketSignal) {
	for _, s := range in {
		switch s.Polarity {
		case models.PolarityPro:
			pros = append(pros, s)
		case models.PolarityCon:
			cons = append(cons, s)
		}
	}
	return pros, cons
}

func joinOrNone(items []string) string {
	if len(items) == 0 {
		return "none"
	}
	return strings.Join(items, ", ")
}

func pluralize(word string, n int) string {
	if n == 1 {
		return word
	}
	return word + "s"
}
