package api

import (
	"strings"
	"testing"
	"time"

	"validator-backend/internal/models"
)

func TestBuildLLMPayload(t *testing.T) {
	idea := &models.Idea{
		Title:         "Cloud Kitchen Inventory SaaS",
		Description:   "Real-time stock tracking for ghost kitchens.",
		FrequencyDays: 3,
		Keywords:      []string{"cloud kitchen", "inventory"},
		Channels:      []string{"reddit", "youtube", "news"},
		CustomChannels: []models.CustomChannel{
			{ID: "c1", URL: "https://example.com", Label: "Competitor"},
		},
	}
	run := &models.ScoutRun{ID: "r1", IdeaID: "i1", DayNumber: 6, Label: "Day 6 Scan", RunAt: time.Now()}
	signals := []models.MarketSignal{
		{ID: "s1", ScoutRunID: "r1", IdeaID: "i1", Polarity: models.PolarityPro, Platform: models.PlatformReddit,
			Quote: "We waste so much food.", Reason: "Pain point.", SourceURL: "https://reddit.com/x", SourceTitle: "T"},
		{ID: "s2", ScoutRunID: "r1", IdeaID: "i1", Polarity: models.PolarityCon, Platform: models.PlatformNews,
			Quote: "Oversaturation in metros.", Reason: "Saturation.", SourceURL: "https://news.com/y", SourceTitle: "T2"},
	}

	out := BuildLLMPayload(idea, run, signals)

	checks := []string{
		"# IDEA: Cloud Kitchen Inventory SaaS",
		"## DESCRIPTION",
		"Real-time stock tracking for ghost kitchens.",
		"## SEARCH RADIUS METADATA",
		"**Keywords:** cloud kitchen, inventory",
		"**Channels:** reddit, youtube, news",
		"**Scouting Frequency:** Every 3 days",
		"**Custom Sources:**",
		"- Competitor: https://example.com",
		"## CYCLE: Day 6 Scan (Day 6)",
		"### RAW PROS FOUND:",
		"[REDDIT] https://reddit.com/x",
		"> \"We waste so much food.\"",
		"**Why it's a Pro:** Pain point.",
		"### RAW CONS FOUND:",
		"[NEWS] https://news.com/y",
		"**Why it's a Con:** Saturation.",
		"---",
		"*Generated by Validator - Agentic Market Research*",
	}
	for _, c := range checks {
		if !strings.Contains(out, c) {
			t.Errorf("payload missing %q\n--- payload ---\n%s", c, out)
		}
	}
}

func TestBuildLLMPayload_PluralizationSingleDay(t *testing.T) {
	idea := &models.Idea{Title: "X", Description: "d", FrequencyDays: 1, Keywords: []string{"k"}, Channels: []string{"reddit"}}
	out := BuildLLMPayload(idea, nil, nil)
	if !strings.Contains(out, "**Scouting Frequency:** Every 1 day\n") {
		t.Fatalf("expected singular 'day', got:\n%s", out)
	}
	if !strings.Contains(out, "_No signals found this cycle._") {
		t.Fatalf("expected empty-signal placeholder, got:\n%s", out)
	}
}
