import { useState, useRef, useEffect } from 'react';
import { Idea, ScoutCycle } from '../types';
import { useTheme } from '../context/ThemeContext';
import { Copy, Check, ChevronDown, Sparkles, X } from '../components/Icons';

interface CopyToLLMProps {
  idea: Idea;
  selectedCycle: ScoutCycle | null;
}

const llmOptions = [
  { id: 'chatgpt', label: 'ChatGPT', url: 'https://chat.openai.com' },
  { id: 'claude', label: 'Claude', url: 'https://claude.ai' },
  { id: 'gemini', label: 'Gemini', url: 'https://gemini.google.com' },
];

export function CopyToLLM({ idea, selectedCycle }: CopyToLLMProps) {
  const { theme } = useTheme();
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [selectedLLM, setSelectedLLM] = useState<string | null>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const generatePayload = () => {
    const cycle = selectedCycle || idea.cycles[idea.cycles.length - 1];
    if (!cycle) return '';

    const customSourcesSection = idea.customChannels && idea.customChannels.length > 0
      ? `**Custom Sources:**\n${idea.customChannels.map(c => `- ${c.label}: ${c.url}`).join('\n')}`
      : '';

    const sections = [
      `# IDEA: ${idea.title}`,
      '',
      `## DESCRIPTION`,
      idea.description,
      '',
      `## SEARCH RADIUS METADATA`,
      `**Keywords:** ${idea.keywords.join(', ')}`,
      `**Channels:** ${idea.channels.join(', ')}`,
      `**Scouting Frequency:** Every ${idea.scoutingFrequencyDays} ${idea.scoutingFrequencyDays === 1 ? 'day' : 'days'}`,
      customSourcesSection,
      '',
      `## CYCLE: ${cycle.label} (Day ${cycle.day})`,
      '',
      `### RAW PROS FOUND:`,
      ...cycle.pros.map((p) => `[${p.platform.toUpperCase()}] ${p.sourceUrl}\n> "${p.quote}"\n**Why it's a Pro:** ${p.reason}\n`),
      '',
      `### RAW CONS FOUND:`,
      ...cycle.cons.map((c) => `[${c.platform.toUpperCase()}] ${c.sourceUrl}\n> "${c.quote}"\n**Why it's a Con:** ${c.reason}\n`),
      '',
      `---`,
      `*Generated by Validator - Agentic Market Research*`,
    ].filter(Boolean);

    return sections.join('\n');
  };

  const handleCopy = async (llmId?: string) => {
    const payload = generatePayload();
    try {
      await navigator.clipboard.writeText(payload);
      setCopied(true);
      if (llmId) {
        setSelectedLLM(llmId);
      }
      setTimeout(() => {
        setCopied(false);
        setIsOpen(false);
      }, 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const payload = generatePayload();

  return (
    <div className={`p-5 rounded-2xl border transition-all duration-300 ${
      theme === 'dark'
        ? 'bg-zinc-900 border-zinc-800'
        : 'bg-white border-zinc-200'
    }`}>
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className={`p-2.5 rounded-xl ${
            theme === 'dark'
              ? 'bg-gradient-to-br from-violet-500/20 to-purple-500/20'
              : 'bg-gradient-to-br from-violet-100 to-purple-100'
          }`}>
            <Sparkles className={`w-5 h-5 ${
              theme === 'dark' ? 'text-violet-400' : 'text-violet-600'
            }`} />
          </div>
          <div>
            <h3 className={`font-semibold ${
              theme === 'dark' ? 'text-zinc-100' : 'text-zinc-900'
            }`}>
              Ready for LLM Analysis
            </h3>
            <p className={`text-sm ${
              theme === 'dark' ? 'text-zinc-400' : 'text-zinc-600'
            }`}>
              Copy compiled data to analyze with your AI assistant
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2" ref={dropdownRef}>
          <div className="relative">
            <button
              onClick={() => setIsOpen(!isOpen)}
              className={`flex items-center gap-2 px-5 py-3 rounded-xl font-semibold text-sm transition-all duration-300 ${
                copied
                  ? 'bg-gradient-to-r from-emerald-500 to-teal-500 text-white'
                  : theme === 'dark'
                    ? 'bg-gradient-to-r from-violet-600 to-purple-600 text-white hover:from-violet-500 hover:to-purple-500 shadow-lg shadow-violet-500/25'
                    : 'bg-gradient-to-r from-violet-500 to-purple-500 text-white hover:from-violet-400 hover:to-purple-400 shadow-lg shadow-violet-500/25'
              }`}
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Copy to LLM
                  <ChevronDown className={`w-4 h-4 transition-transform duration-200 ${isOpen ? 'rotate-180' : ''}`} />
                </>
              )}
            </button>

            {isOpen && (
              <div className={`absolute top-full left-0 mt-2 w-48 rounded-xl border shadow-xl z-50 overflow-hidden ${
                theme === 'dark'
                  ? 'bg-zinc-800 border-zinc-700'
                  : 'bg-white border-zinc-200'
              }`}>
                {llmOptions.map((llm) => (
                  <button
                    key={llm.id}
                    onClick={() => handleCopy(llm.id)}
                    className={`w-full flex items-center gap-2 px-4 py-3 text-sm font-medium transition-colors ${
                      theme === 'dark'
                        ? 'text-zinc-300 hover:bg-zinc-700'
                        : 'text-zinc-700 hover:bg-zinc-50'
                    }`}
                  >
                    {selectedLLM === llm.id && copied ? (
                      <Check className="w-4 h-4 text-emerald-500" />
                    ) : (
                      <Copy className="w-4 h-4" />
                    )}
                    Copy for {llm.label}
                  </button>
                ))}
              </div>
            )}
            </div>

          <button
            onClick={() => setShowPreview(!showPreview)}
            className={`px-4 py-3 rounded-xl text-sm font-medium transition-all duration-200 ${
              theme === 'dark'
                ? 'bg-zinc-800 text-zinc-300 hover:bg-zinc-700'
                : 'bg-zinc-100 text-zinc-600 hover:bg-zinc-200'
            }`}
          >
            {showPreview ? 'Hide' : 'Preview'}
          </button>
        </div>
      </div>

      {/* Preview Accordion */}
      <div className={`overflow-hidden transition-all duration-500 ease-out ${
        showPreview ? 'max-h-[600px] opacity-100 mt-4' : 'max-h-0 opacity-0'
      }`}>
        <div className={`rounded-xl border overflow-hidden ${
          theme === 'dark' ? 'bg-zinc-800 border-zinc-700' : 'bg-zinc-50 border-zinc-200'
        }`}>
          <div className={`flex items-center justify-between px-4 py-3 border-b ${
            theme === 'dark' ? 'border-zinc-700' : 'border-zinc-200'
          }`}>
            <span className={`text-xs font-semibold uppercase tracking-wide ${
              theme === 'dark' ? 'text-zinc-400' : 'text-zinc-500'
            }`}>
              Markdown Payload Preview
            </span>
            <button
              onClick={() => setShowPreview(false)}
              className={`p-1 rounded transition-colors ${
                theme === 'dark' ? 'hover:bg-zinc-700' : 'hover:bg-zinc-200'
              }`}
            >
              <X className={`w-4 h-4 ${
                theme === 'dark' ? 'text-zinc-400' : 'text-zinc-500'
              }`} />
            </button>
          </div>
          <pre className={`p-4 text-xs overflow-auto max-h-[400px] whitespace-pre-wrap ${
            theme === 'dark' ? 'text-zinc-300' : 'text-zinc-700'
          }`}>
            {payload}
          </pre>
        </div>
      </div>
    </div>
  );
}
